name: Publish docs to GitHub Pages

on:
  push:
    branches:
      - main

# Grant the workflow the minimum permissions it needs
permissions:
  pages: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo root
        run: |
          echo "Current dir: $(pwd)"
          echo "List top-level files:" 
          ls -la || true

      - name: List docs
        run: |
          echo "Listing docs folder contents (if present):"
          if [ -d docs ]; then ls -la docs; else echo "docs/ not found"; fi

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
