name: Pages sanity check

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo root
        run: |
          echo "Current dir: $(pwd)"
          echo "List top-level files:" 
          ls -la || true

      - name: List docs
        run: |
          echo "Listing docs folder contents (if present):"
          if [ -d docs ]; then ls -la docs; else echo "docs/ not found"; fi

      - name: Sanity success
        run: echo "Pages runner sanity check completed"
